### ISSUE TITLE
Mauve-py install appears to fail

### ISSUE THREAD

**Issue by glebkuznetsov** [Wyss/mascpcr#2]
Tests and general use of the library is currently broken following fresh install. My install procedure:

1. Create new virtualenv

2. Activate venv and follow pip install directions in README.md. Also installed `nose` for running tests.

3. Try running a test using command, e.g.:

        $ nosetests tests/test_pipeline.py

Observed error relating to something missing in mauve (pasted below). Looking in the venv where mauve is installed, I don't see the expected `bin/` dir.

Full error paste:

(venv)gleb@glebs-mbp.hsd1.ma.comcast.net:~/Dropbox/Backup/Projects/churchlab/mascpcr$ python tests/test_pipeline.py
Traceback (most recent call last):
  File "tests/test_pipeline.py", line 5, in <module>
    from mascpcr import pipeline, genbankfeatures
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/mascpcr/mascpcr/__init__.py", line 44, in <module>
    from . import indexing, ioutil, offtarget, pipeline, primercandidate, \
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/mascpcr/mascpcr/indexing.py", line 36, in <module>
    import mauve
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/mascpcr/venv/lib/python2.7/site-packages/mauve/__init__.py", line 12, in <module>
    from .buildindex import buildIndex
  File "/Users/gleb/Dropbox/Backup/Projects/churchlab/mascpcr/venv/lib/python2.7/site-packages/mauve/buildindex.py", line 21, in <module>
    MAUVE_DIR, os.environ.get('MAUVE_DIR')))
IOError: Cache could not find progressiveMauveStatic in /Users/gleb/Dropbox/Backup/Projects/churchlab/mascpcr/venv/lib/python2.7/site-packages/mauve/src/bin. Environmental variable `MAUVE_DIR` is defined as: /Users/gleb/Dropbox/Backup/Projects/churchlab/mascpcr/venv/lib/python2.7/site-packages/mauve/src/bin.

**Comment by benpruitt** [comment]
Which version of OS X are you running? Also, do you have boost installed?

**Comment by glebkuznetsov** [comment]
I'm running OS X Mavericks 10.9.5. I do have boost installed (boost-1.56.0).

**Comment by grinner** [comment]
Is the progressiveMauveStatic binary where it is supposed to be?

-Nick

**Comment by grinner** [comment]
This issue should probably be in mauve-py repo
